### ISSUE TITLE
Do I need Roslyn to get it to work?

### ISSUE THREAD

**Issue by HJLebbink** [smourier/EnumCaseGenerator#1]
I'd like to use this extension, but I can't seem to get it to work. I have VS2017 (15.4.0), the extension has been installed without warnings. Is there something else needed? You mention that it is developed using Roslyn, does that mean I need to install something to get the extension to work?

**Comment by smourier** [comment]
Hi,

Thanks for pointing that out. I seems it does not work any more on VS 2015 and VS2017! I'm having a look into it and have no idea what's going on. It doesn't even work on my dev PC, w/o any error it just doesn't load. It looks like they changed something... keep you posted

**Comment by smourier** [comment]
It ... seems ... it fixed itself with Visual Studio Updates. In my case it works fine now, I have Visual Studio 2017 15.4.2
